# The vic3-tiger.conf file is in standard Paradox script format.
# It should be placed in the top directory of your mod.

languages = {
	check = "english"
    check = "braz_por"
    check = "french"
    check = "german"
    check = "polish"
    check = "russian"
    check = "spanish"
    check = "japanese"
    check = "simp_chinese"
    check = "korean"
    check = "turkish"
}

# Allows configuring what reports are printed
filter = {

    # Whether to report about problems in vanilla game files.
    # Setting this to 'yes' results in a LOT of spam.
    # Optional boolean value, defaults to no.
    show_vanilla = no

    # Whether to report about problems in mods loaded via the load_mod sections.
    # Optional boolean value, defaults to no.
    show_loaded_mods = no

    # Contains rules for reports, using trigger syntax.
    # Only reports matching the trigger will be printed.
    # The root trigger is an AND block, just like any other trigger.
    trigger = {
        # For more information, there is a guide at: ck3-tiger/filter.md
        # In short, valid trigger keys are:
        # - always = yes/no
        # - NOT, AND, OR, NAND, NOR
        # - severity
        # - confidence
        # - key
        # - file
        # - text
        # - ignore_keys_in_files
        NOR = {
            
            # Ignore unit modifiers not flowing from building
            # This is known & the unit modifiers only exist for presentation
            AND = {
                key  = modifiers
                text = "is a modifier for unit"
                text = "will not flow from building"
            }
            
            # False positive regarding using scope:state in modifier multipliers
            AND = {
                key  = strict-scopes
                text = "scope:state might not be available here"
            }
            
            # False positive regarding redefinitions in INJECTed definitions
            AND = {
                key = duplicate-field
                OR  = {
                    AND = {
                        file = "common/combat_unit_types/FAE_combat_unit_types.txt"
                        text = "`battle_modifier` is redefined in a following line"
                    }
                    AND = {
                        file = "common/technology/technologies/FAE_technologies.txt"
                        text = "`modifier` is redefined in a following line"
                    }
                }
            }
            
        }
    }
}
